### ISSUE TITLE
Authors tab Acknowledgement text modification

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/CougarStats#22]
@samantha-v-brian 

In the Authors tabPanel() we currently have this text:

Acknowledgement: In Fall 2022 an earlier version of this interactive R Shiny app was presented as Crystal Wai's COMP 5690: Senior Computer Science Project. From June - August 2023 this project was funded by a student research grant (awarded to Michael Myer) conferred by the Faculty of Science and Technology at Mount Royal University. Starting September 2023 this project is funded by a Provost's Teaching-Learning Enhancement Grant (TLEG). Michael Myer is currently hired as a Project Assistant through this grant.

Change it to the following

**Acknowledgement:** In Fall 2022 an earlier version of this interactive R Shiny app was presented as Crystal Wai's COMP 5690: Senior Computer Science Project. From June - August 2023 this project was funded by a student research grant conferred by the Faculty of Science and Technology at Mount Royal University. From September 2023 - April 2024 this project was funded by a Provost's Teaching-Learning Enhancement Grant (TLEG). Starting July 2024 this project will be funded by the Provost's Teaching-Learning Enhancement Grant (TLEG) for the 2024-2025 cycle.

**Comment by ashokkrish** [comment]
@bryce-carson 

Remove Michael Myer, Samantha Brian and Michael Walsh. Add your name a a Senior Developer.

Change it to the following

**Acknowledgement:** The development of this interactive R Shiny app has benefited from the contributions of several students. In Fall 2022, Crystal Wai presented an early version of this app as part of her COMP 5690: Senior Computer Science Project. From June to August 2023, Michael Myer further developed the project, supported by a student research grant from the Faculty of Science and Technology at Mount Royal University. From September 2023 to April 2024, Michael Myer continued his work on the project with funding from a Provost's Teaching-Learning Enhancement Grant (TLEG). Beginning in October 2024, this project will receive continued support through the TLEG for the 2024-2025 cycle.

**Comment by bryce-carson** [comment]
@ashokkrish, I resolved the broken image issue by using text only, following the trademark and branding guidelines from Posit.

https://posit.co/about/trademark-guidelines/

**Comment by ashokkrish** [comment]
@bryce-carson 

Could you make the same changes to the README.Md file on the GitHub repository please?

**Comment by bryce-carson** [comment]
@ashokkrish, please see the linked commit message for a small opinionated change.
