### ISSUE TITLE
Constructing a Pie or Bar Chart

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/CougarStats#3]
@bryce-carson 

<img width="377" alt="image" src="https://github.com/ashokkrish/CougarStats/assets/410949/979870b4-1f6e-4a34-a31b-5e5b444e57d5"> 

when the parameter of interest is

<img width="207" alt="image" src="https://github.com/user-attachments/assets/ed14ebc6-dfce-478d-8495-2c45104b0881">

just above the **Calculate** button place a dropdown with multi select = T

<img width="382" alt="image" src="https://github.com/ashokkrish/CougarStats/assets/410949/f1bc104a-f3a7-4411-b5db-ab73667412d2">

that’ll construct a pie chart and/or a bar chart for the number of successes (x) and number of failures (n - x).

The charts would look something like this

 <img width="201" alt="image" src="https://github.com/ashokkrish/CougarStats/assets/410949/a03b0c1b-ae90-4702-8628-d06de28db278">

or

<img width="398" alt="image" src="https://github.com/ashokkrish/CougarStats/assets/410949/32038453-efe6-4002-9d2b-4b8d179523ae">

On the mainPanel add another tabPanel called 'Graphs' with the selected plot(s) rendered. I recommend using ggplot for these plots. For reference you can see how we have a dropdown for plots under **Descriptive Statistics** Please do not hesitate to reach out to me if you have any further questions.

**Comment by ashokkrish** [comment]
@mwals360 

Further to our discussion let's add another tabPanel called 'Graphs' with these two plots rendered. I recommend using ggplot for these plots. Please do not hesitate to reach out to me if you have any further questions.

**Comment by ashokkrish** [comment]
> just plot both visualizations

@bryce-carson I agree. Let's plot both of them.

**Comment by bryce-carson** [comment]
@ashokkrish I have finished this task.
