### ISSUE TITLE
Changes to README.Md

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/CougarStats#34]
@bryce-carson

Could you make the following changes to the README.Md file on the GitHub repository please?

Acknowledgement: The development of this interactive R Shiny app has benefited from the contributions of several students. In Fall 2022, Crystal Wai presented an early version of this app as part of her COMP 5690: Senior Computer Science Project. From June to August 2023, Michael Myer further developed the project, supported by a student research grant from the Faculty of Science and Technology at Mount Royal University. From September 2023 to April 2024, Michael Myer continued his work on the project with funding from a Provost's Teaching-Learning Enhancement Grant (TLEG). Beginning in October 2024, this project will receive continued support through the TLEG for the 2024-2025 cycle.

Remove Michael Myer and Michael Walsh from the Authors tab. Add your name and Samantha Brian as a Developer.

**Comment by bryce-carson** [comment]
What do you think about this alternate formatting, @ashokkrish?

| Grant and/or Funding Agency | Recipient | Date(s) |
|--------|--------|--------|
| FST Mount Royal University Student Research Grant | Michael Myer | June through August 2023 |
| Provost's Teaching-Learning Enhancement Grant (TLEG) | Michael Myer | September 2023 through April 2024 |
| TLEG | Bryce Carson | November 2024 through January 2025 |
| TLEG | Samantha Brian | January 2024 through T.B.D. |

**Comment by bryce-carson** [comment]
Grant numbers and other things can be provided in further columns, or added to the cell values for the first column.

**Comment by bryce-carson** [comment]
This formatting would be useful for similar or identical content within the Shiny applications.

**Comment by ashokkrish** [comment]
> What do you think about this alternate formatting, @ashokkrish?
> 
> Grant and/or Funding Agency	Recipient	Date(s)
> FST Mount Royal University Student Research Grant	Michael Myer	June through August 2023
> Provost's Teaching-Learning Enhancement Grant (TLEG)	Michael Myer	September 2023 through April 2024
> TLEG	Bryce Carson	November 2024 through January 2025
> TLEG	Samantha Brian	January 2024 through T.B.D.

I like this. Let's go with this table.
