### ISSUE TITLE
Dark Mode toggle button position

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/CougarStats#36]
@bryce-carson 

I would like the  toggle

<img width="127" alt="image" src="https://github.com/user-attachments/assets/3e49e441-a38e-4039-b684-22fce8b86f38">

moved to the top right corner.

Also by default I want the Dark Mode OFF.

**Comment by bryce-carson** [comment]
Append to DOM element with id `mainPanel`, set style of appended element to `margin-left: auto`.

**Comment by bryce-carson** [comment]
`div.container-fluid:has-child('li#main-banner')` should do it too.

How to render HTML from R, but not insert into DOM? Need the following HTML to hack into UI with JS:
```R
  tags$div(style = "margin-left: auto",
           prettySwitch(inputId = "togglemode",
                        label = "Dark Mode",
                        value = FALSE,
                        fill = TRUE,
                        status = "primary"))
```

**Comment by ashokkrish** [comment]
@bryce-carson I added the above to ui.R and got this

<img width="542" alt="image" src="https://github.com/user-attachments/assets/2cdf2234-4cd5-4197-9f31-0ff5345e6688">

**Comment by bryce-carson** [comment]
@ashokkrish, okay; good try. I'm working on this. I'll have it correct in a moment; I made those comments for myself as notes in case I didn't return to the issue or got distracted by something.

**Comment by bryce-carson** [comment]
This solution isn't working as expected. I'll investigate it more some other time, after #33 and the other discussed feature are working.

**Comment by bryce-carson** [comment]
See this blog post: https://shiny.posit.co/blog/posts/shiny-r-1.8.0/

Shiny v1.8.0 and bslib v0.6.0 support built-in darkmode. Using thematic:

> Simplified theming of [ggplot2](https://ggplot2.tidyverse.org/), [lattice](https://lattice.r-forge.r-project.org/), and {base} R graphics. In addition to providing a [centralized approach](https://rstudio.github.io/thematic/articles/custom.html) to styling R graphics, [thematic](https://rstudio.github.io/thematic/) also enables [automatic styling](https://rstudio.github.io/thematic/articles/auto.html) of R plots in Shiny, R Markdown, and RStudio. 

### NOTES
- https://shiny.posit.co/blog/posts/shiny-r-1.8.0/#release-notes
- https://rstudio.github.io/thematic/index.html

### Conclusion
Recent versions of shiny and bslib obsolete [deepanshu88/shinyDarkmode](https://github.com/deepanshu88/shinyDarkmode), which hasn't had any updates for two years.
