### ISSUE TITLE
Mobile UI

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/CougarStats#40]
The UI is not [responsive or adaptive](https://www.interaction-design.org/literature/article/adaptive-vs-responsive-design?srsltid=AfmBOoq1ZxDizpZ0e9c-8xNPoIHAblITeruMPJmFyDZQUgo4ziyWXabL). It should be.

**Comment by bryce-carson** [comment]
https://shiny.posit.co/r/articles/build/layout-guide/

**Comment by bryce-carson** [comment]
![Screenshot at 2024-12-09 23-47-34](https://github.com/user-attachments/assets/b542a44a-7d49-4010-a3f5-bc3c5d94a905)

@ashokkrish this is how the application appears on my Android, which is not a small device. The UI is not friendly for mobile devices.

**Comment by ashokkrish** [comment]
@bryce-carson > The UI is not friendly for mobile devices

I would not worry too much about the mobile UI as we are pursuing independent iOS (already at 300 downloads on the Appstore) and Android apps.

**Comment by bryce-carson** [comment]
> > The UI is not friendly for mobile devices
> 
> I would not worry too much about the mobile UI as we are pursuing independent iOS (already at 300 downloads on the Appstore) and Android apps.
> 
> We can revisit this later.
> --- @ashokkrish 

Alright.
