### ISSUE TITLE
Non-syntactic names in explanatory and response variable names in MLR example 5 cause application crash

### ISSUE THREAD

**Issue by bryce-carson** [ashokkrish/CougarStats#52]
> CougarStats app is crashing when I run this MLR example.
> 
> Here Systolic pressure 5–10 years later is the response variable (y) while the columns Systolic pressure At transplant (x1), Gender (x2) and Age(years) (x3) are the explanatory variables.
> 
> Can you take a look at why this is crashing? This Google Doc has the solutions from the source.

https://docs.google.com/document/d/1kdSflVlXlWsXuopUUQZ0ai8SNkyHUpAto3Mk-z-I4Nc/edit?usp=sharing

**Comment by bryce-carson** [comment]
```
Warning: Error in str2lang: <text>:1:10: unexpected symbol
1: Systolic pressure
             ^
  96: str2lang
  95: reformulate
  90: eval [R/multipleLinearRegression.R#260]
  89: eval
  88: with.default
  86: observe [R/multipleLinearRegression.R#254]
  85: <observer>
   6: runApp
   5: print.shiny.appobj
   3: ss
   2: .ess.source
   1: base::as.environment("ESSR")$.ess.eval
```

Evidently, str2lang throws an error because the symbol "Systolic pressure" is non-syntactic, but it not accessed in a non-syntactic manner.

```R
      with(uploadedTibble$data(), {
        ## REDACTED
        model <- lm(reformulate(input$explanatoryVariables, input$responseVariable))
```

The columns of the tibble supplied by the reactive `uploadedTibble$data()` are made available in the environment, and reformulate will access these from the environment using _the strings_ returned by `input$explanatoryVariables`.

- Symptom: a str2lang error caused by reformulate using a variable with spaces in it.
- Resolution:
  - Experiment with reformulate: `` `non-syntactic symbols?` ``, `"strings"`, `syntacticSymbols`.
  - Experiment with `as.name()`

```

> ?str2lang
> ??symbols
> as.name("Non-syntactic strings")
`Non-syntactic strings`
> as.name(c("Non-syntactic strings", "syntacticStrings", "?"))
`Non-syntactic strings`
> lapply(c("Non-syntactic strings", "syntacticStrings", "?"), as.name)
[[1]]
`Non-syntactic strings`

[[2]]
syntacticStrings

[[3]]
`?`

> 
```

# Conclusion
The documentation for `reformulate` states that non-syntactic names must be manually handled, so `reformulate(lapply(input$explanatoryVariables, as.name))` should be a sufficient fix.

```
     ‘reformulate’ creates a formula from a character vector.  If
     ‘length(termlabels) > 1’, its elements are concatenated with ‘+’.
     Non-syntactic names (e.g. containing spaces or special characters;
     see make.names) must be protected with backticks (see examples).
     A non-parseable ‘response’ still works for now, back compatibly,
     with a deprecation warning.
```

**Comment by bryce-carson** [comment]
![Screenshot 2024-12-27 at 15-11-39 ](https://github.com/user-attachments/assets/e4df5015-a039-4989-a6d1-2cabbfb658d9)

**Comment by ashokkrish** [comment]
Results not matching.
