### ISSUE TITLE
Statistical Inference for One Population Standard Deviation: Confidence Interval

### ISSUE THREAD

**Issue by ashokkrish** [ashokkrish/CougarStats#6]
@samantha-v-brian 

When the user selects

<img width="379" alt="image" src="https://github.com/ashokkrish/CougarStats/assets/410949/b4ea61e1-edad-46cc-8954-33d4215d51f9">

Currently there are two parameters of interest to choose from

<img width="295" alt="image" src="https://github.com/ashokkrish/CougarStats/assets/410949/63a5e63a-b76f-4891-b7b6-fff9e3c53c18">

I would like to add another parameter of interest to this list and make it look like this 

<img width="202" alt="image" src="https://github.com/ashokkrish/CougarStats/assets/410949/b27060d6-ed30-46d4-94e9-dd5c86e69f92">

It can be achieved by the following code

```
                radioButtons(
                  inputId      = "popuParameter",
                  label        = strong("Parameter of Interest"),
                  choiceValues = list("Population Mean", 
                                      "Population Standard Deviation", 
                                      "Population Proportion"),
                  choiceNames  = list("Population Mean (\\( \\mu \\)) ", 
                                      "Population Standard Deviation (\\( \\sigma \\)) ", 
                                      "Population Proportion (\\( p\\))"),
                  selected     = "Population Mean", #character(0), #
                  inline       = FALSE), #,width = '1000px'),
```

Now suppose the user selects
 
<img width="201" alt="image" src="https://github.com/ashokkrish/CougarStats/assets/410949/30ef48f7-eb9a-4ee4-ada8-3eeb27d59eb8">

We should have two numericInputs called

Sample Size (n)
Population Standard Deviation (σ)

Validate the above two fields:

- Sample Size cannot be empty, it has to be a positive integer greater than zero.
- Population Standard Deviation cannot be empty, it has to be a positive value (decimals allowed) greater than zero.

Next we will have a radio button toggle as follows

<img width="245" alt="image" src="https://github.com/ashokkrish/CougarStats/assets/410949/5ef8d450-28ac-4938-9a20-8d1c585303ac">

In the user selects Confidence Interval then display the following Confidence Level choices

<img width="147" alt="image" src="https://github.com/ashokkrish/CougarStats/assets/410949/b7648936-f11c-4f3c-a77e-a3aedc5e05a8">

In the user selects Hypothesis Testing then display the following

<img width="129" alt="image" src="https://github.com/ashokkrish/CougarStats/assets/410949/f5d8d188-1e0e-4d8e-bbb2-5c21ddcdcfe9">

Followed by a numericInput for 

Hypothesized Population Mean (σ0) Value

Following that have this

<img width="381" alt="image" src="https://github.com/ashokkrish/CougarStats/assets/410949/88951abd-7cee-4547-8a9a-d7ae4de1d2ed">

**Comment by samantha-v-brian** [comment]
Hi Ashok!
I've added the Population Standard Deviation radio button, as well as conditional panels for Sample Size (n) and Population Standard Deviation (σ). The conditional panels for Inference Types are both functioning per Mike Meyer's previous work.

Can you expand more on the Hypothesized Population Mean value? Additionally, is there a document I can refer to for sample values + calculations so I can test if these additions are working?

**Comment by ashokkrish** [comment]
@samantha-v-brian 

Hi Sam,

Thanks for working on this issue. Here are some follow-up requests on this same issue.

- I made a mistake in the header of one of the numericInputs, can you change <img width="203" alt="image" src="https://github.com/ashokkrish/CougarStats/assets/410949/866c8771-65f1-424f-81f1-582e1104c7e8"> to Sample Standard Deviation (_s_)?
- Set a default value for <img width="89" alt="image" src="https://github.com/ashokkrish/CougarStats/assets/410949/aae023a7-be07-41ef-8330-d26595a3b001"> as 30.
- Set a default value for Sample Standard Deviation (_s_) as 12.23.
- Italicize <img width="89" alt="image" src="https://github.com/ashokkrish/CougarStats/assets/410949/be306270-59dd-423d-aaa8-03ce643c70e0">
- If either of these two fields are left blank and the user clicks the Calculate button
<img width="377" alt="image" src="https://github.com/ashokkrish/CougarStats/assets/410949/4ba07f6e-fb74-4714-9245-f37cb5383263">

Display the following messages
<img width="288" alt="image" src="https://github.com/ashokkrish/CougarStats/assets/410949/23c2eb1d-3f91-4710-ac62-4d05a41100a3">

<img width="272" alt="image" src="https://github.com/ashokkrish/CougarStats/assets/410949/b5390b4f-6b85-4a70-bdf1-1d441b34911b">


- Here is a test case for a 90% confidence interval
<img width="373" alt="image" src="https://github.com/ashokkrish/CougarStats/assets/410949/bcf5a8d4-559c-4e92-8ed2-ec8df36656c0">

On the mainPanel after all the validation checks out we will print the answer showing all the steps. For now if you can fix the above requests and push the code that'd great.

**Comment by ashokkrish** [comment]
For the radioButton could you set **inline = FALSE**? This will set the options as follows

<img width="299" alt="image" src="https://github.com/ashokkrish/CougarStats/assets/410949/eb3338bd-402f-467b-a6d5-d5299cf82202">

**Comment by samantha-v-brian** [comment]
Hi Ashok!

The above requests have been fixed. I also added main panel error messages for Sample Size Estimation per the task on Google Docs, as I'd missed them previously when implementing validation.

**Comment by ashokkrish** [comment]
I am sorry about a minor confusion and it is entirely my fault, 

In the radioButton choices it should be 
![image](https://github.com/ashokkrish/CougarStats/assets/410949/81c932b4-405b-44f9-bf79-da0c425ff4af)

but the numericInput should be 
<img width="182" alt="image" src="https://github.com/ashokkrish/CougarStats/assets/410949/e7101c2c-1042-40b7-b61d-434a9262ea77">

In other words Population Standard Deviation is the Parameter of Interest and the Sample Standard Deviation is its point estimate.

**Comment by samantha-v-brian** [comment]
Not a problem, it was an easy fix. I've pushed the change.

**Comment by bryce-carson** [comment]
> <img alt="image" width="373" src="https://private-user-images.githubusercontent.com/410949/332275404-bcf5a8d4-559c-4e92-8ed2-ec8df36656c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MzI3MTcsIm5iZiI6MTcyOTUzMjQxNywicGF0aCI6Ii80MTA5NDkvMzMyMjc1NDA0LWJjZjVhOGQ0LTU1OWMtNGU5Mi04ZWQyLWVjOGRmMzY2NTZjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQxNzQwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzBlNzI3MWI3NmM2MDNhZmZhZjcxNWUwZWM1MWQ3MjliZTQxNDY2MzRmODFkOTZlYWM1MzVhODViN2I2MzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PQ_ahdWPAc8HfYd48B-c39iEmOhmFb_S6WIfgNuTl-Q">

These formulae need to be the radicand so that the standard deviation is calculated, not the variance (as depicted); right, @ashokkrish?

**Comment by ashokkrish** [comment]
@bryce-carson Yes, that's correct. Here is a another breakdown of steps,

<img width="410" alt="image" src="https://github.com/user-attachments/assets/9fbd7b1d-f18e-4709-a508-d92416c20a36">

Here is another fully worked out example

<img width="421" alt="image" src="https://github.com/user-attachments/assets/868f7bd6-6db1-41b7-a947-9173ce77ebf5">

**Comment by bryce-carson** [comment]
> @bryce-carson Yes, that's correct. Here is a another breakdown of steps,
> <img alt="image" width="410" src="https://private-user-images.githubusercontent.com/410949/378541871-9fbd7b1d-f18e-4709-a508-d92416c20a36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MzQyMDQsIm5iZiI6MTcyOTUzMzkwNCwicGF0aCI6Ii80MTA5NDkvMzc4NTQxODcxLTlmYmQ3YjFkLWYxOGUtNDcwOS1hNTA4LWQ5MjQxNmMyMGEzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQxODA1MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDZhNTFmYjMxNzAwMmJiZmEzNDlkNDBjNmIzZGQ3YWY1NTQ0YmFhZmVjMjAwMjAwNGI0MzJjYmY5MzY4YmFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mTKoO4K0a9HDmwfSOYr2_cRnsXLuy76P03iGZ2T8BOk">
> 
> Here is another fully worked out example
> <img alt="image" width="421" src="https://private-user-images.githubusercontent.com/410949/378542882-e5c7db08-8851-4b36-924f-f412d66a7c8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MzQyMDQsIm5iZiI6MTcyOTUzMzkwNCwicGF0aCI6Ii80MTA5NDkvMzc4NTQyODgyLWU1YzdkYjA4LTg4NTEtNGIzNi05MjRmLWY0MTJkNjZhN2M4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQxODA1MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xN2Y0OTgyYmNkZGJjZjI2NzU4YmYzOTA3OTJhMWQyZWNkMWNjYzYyMzQ4NGE4MTRiZGU3MmQyYTNkMTE1MGMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eiMntzZuWrOplsSsZn2ytXyTetnM1TuJ05Z3N7k4HNg">

Those reference materials work perfectly for me. Thanks.

**Comment by ashokkrish** [comment]
Couple of examples to check the confidence interval results

<img width="429" alt="image" src="https://github.com/user-attachments/assets/0a24f93b-b462-4ae9-ac68-e484c2ea67b0">

<img width="437" alt="image" src="https://github.com/user-attachments/assets/2907d4c1-0b32-446e-813b-0d574b54b81d">

**Comment by ashokkrish** [comment]
<img width="509" alt="image" src="https://github.com/user-attachments/assets/37bcadea-c918-405b-a0f3-1508f7426cd2">

**Comment by bryce-carson** [comment]
https://www.easysevens.com/understanding-chi-square-critical-value-a-beginners-tutorial/

This really helped me.

**Comment by bryce-carson** [comment]
> <img alt="image" width="509" src="https://private-user-images.githubusercontent.com/410949/379687769-37bcadea-c918-405b-a0f3-1508f7426cd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3OTUwODYsIm5iZiI6MTcyOTc5NDc4NiwicGF0aCI6Ii80MTA5NDkvMzc5Njg3NzY5LTM3YmNhZGVhLWM5MTgtNDA1Yi1hMGYzLTE1MDhmNzQyNmNkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQxODMzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGRkZTAwNGI5YTQzMmFmZjYwYmY3ZTg1NTM0MjMzMWQ5YmI1OTYxMWUzMjcxODAyZDFlY2YwMmZhM2VlODUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ooNS6DFa3EJ1WfoskeO2eQdzx7dOZguu4oxXEhXudY8">
> 
>     * Don't need to bold the text "The confidence interval for σ is from"

For now it doesn't look exactly like that, but we will review it in the meeting.

**Comment by bryce-carson** [comment]
The results are now correct, however.

**Comment by bryce-carson** [comment]
The identifiers aren't the best.

**Comment by ashokkrish** [comment]
@bryce-carson 

<img width="230" alt="image" src="https://github.com/user-attachments/assets/8d10da83-41d9-4a57-a33f-ad32f7d84d5d">

When alpha/2 is calculated you can round it to two-digits not three, e.g.
10% as 0.10 and not 0.100
5% as 0.05 and not 0.050.
1% as 0.01 and not 0.010.

However 

0.05/2 should indeed by 0.025 (three digits)
0.01/2 should indeed me 0.005 (three digits).

**Comment by bryce-carson** [comment]
Returning to work on this tonight. Haven't done anything until now since we last spoke, @ashokkrish.

**Comment by bryce-carson** [comment]
> @bryce-carson
> 
> <img alt="image" width="230" src="https://private-user-images.githubusercontent.com/410949/379929976-8d10da83-41d9-4a57-a33f-ad32f7d84d5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNTcxMzMsIm5iZiI6MTczMjA1NjgzMywicGF0aCI6Ii80MTA5NDkvMzc5OTI5OTc2LThkMTBkYTgzLTQxZDktNGE1Ny1hMzNmLWFkMzJmN2Q4NGQ1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQyMjUzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjRiYWUyNTMxYmE4MjY3ODk4YjNjZGFjNDc1ZDZiZWQzZWE2YjQ5YzliMjQ2ZjExZTQ0N2EzOTYwYjI0N2Q1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VVYpOb3wO0fJADQiPLW5O5FwQ-gO72KOkUyxOvrRjPs">
>
> When alpha/2 is calculated you can round it to two-digits not three, e.g. 10% as 0.10 and not 0.100 5% as 0.05 and not 0.050. 1% as 0.01 and not 0.010.
> 
> However
> 
> 0.05/2 should indeed be 0.025 (three digits) 0.01/2 should indeed be 0.005 (three digits).

@ashokkrish, I do not understand the request for a change here. Your statements are conflicting; do you mean the right-hand side of the equation, the Chi-square test value, should be rounded to two digits? Why mention alpha / 2 at all? I'm sorry, but I'm too confused to move forward on *just* this. Can you elaborate, please?

**Comment by ashokkrish** [comment]
> Why mention alpha / 2 at all?

We are constructing what is called as a two-sided confidence interval. This results in a lower confidence limit (LCL) and an upper confidence limit (UCL). I was simply being a little pick about the number of digits to display. Alpha is typically presented in two digits

10% as 0.10 and not 0.100
5% as 0.05 and not 0.050.
1% as 0.01 and not 0.010.

whereas

0.05/2 should indeed be 0.025 (three digits)
0.01/2 should indeed be 0.005 (three digits).

Does this help?

**Comment by bryce-carson** [comment]
@ashokkrish What I will do for this issue otherwise is ensure that the user-provided values are displayed with the phrasing, "Given n, s, ..." et cetera before the calculations.

**Comment by ashokkrish** [comment]
> @ashokkrish What I will do for this issue otherwise is ensure that the user-provided values are displayed with the phrasing, "Given n, s, ..." et cetera before the calculations.

Follow the exact same format we used for confidence interval for population mean (mu) and population proportion (p).

**Comment by bryce-carson** [comment]
> > Why mention alpha / 2 at all?
> 
> We are constructing what is called as a two-sided confidence interval. This results in a lower confidence limit (LCL) and an upper confidence limit (UCL). I was simply being a little pick about the number of digits to display.

> Alpha is typically presented in two digits
> 
> 10% as 0.10 and not 0.100 5% as 0.05 and not 0.050. 1% as 0.01 and not 0.010.
> 
> whereas
> 
> 0.05/2 should indeed be 0.025 (three digits) 0.01/2 should indeed be 0.005 (three digits).
> 
> Does this help?

*Oh!* Yeah, that helps a lot. I'll reduce the digits of the _alpha_ to two digits, so it displays like below. Is this right?

$$
\chi^2_{1-\alpha/2} = \chi^2_{1-0.05/2} = \chi^2_{0.975}
$$

*rather than*

$$
\chi^2_{1-\alpha/2} = \chi^2_{1-0.050/2} = \chi^2_{0.975}
$$

With the same change for the other side of the confidence interval.

**Comment by bryce-carson** [comment]
> > @ashokkrish What I will do for this issue otherwise is ensure that the user-provided values are displayed with the phrasing, "Given n, s, ..." et cetera before the calculations.
> 
> Follow the exact same format we used for confidence interval for population mean (mu) and population proportion (p).

Will do!

**Comment by ashokkrish** [comment]
> I'll reduce the digits of the _alpha_ to two digits, so it displays like below. Is this right?

This is perfect.

**Comment by bryce-carson** [comment]
@ashokkrish, I have just pushed a commit which changes the formatting to what you desired. Please let me know if it is sufficient and I will close the issue.

**Comment by bryce-carson** [comment]
@ashokkrish I will begin working on #33 now.

**Comment by ashokkrish** [comment]
> @ashokkrish, I have just pushed a commit which changes the formatting to what you desired. Please let me know if it is sufficient and I will close the issue.

@bryce-carson 

If you look at the confidence interval for one population mean (mu) when sigma is unknown you will notice the following

<img width="221" alt="image" src="https://github.com/user-attachments/assets/ea8d39c0-662a-4562-9d3b-1b28734a97ef">

Clarify alpha = **1 - 0.90/0.95/0.99** = 0.10/0.05/0.01

Same way, I would like you to embed the _df_ in the subscripts of the calculations of 

<img width="221" alt="image" src="https://github.com/user-attachments/assets/5879e089-f32d-41fd-835c-5f1b46372573">

**Comment by ashokkrish** [comment]
@bryce-carson 

<img width="564" alt="image" src="https://github.com/user-attachments/assets/bb6308a4-6e91-49bd-9a73-64243c661217">

Left indent this and add a break between the rows.

**Comment by ashokkrish** [comment]
@bryce-carson 

<img width="208" alt="image" src="https://github.com/user-attachments/assets/7b2c8752-52ff-4ffd-8a97-5080177bc84d">

Drop the word _**and**_ in the middle. 
Include text _**df**_ in the subscript of the formula.

<img width="526" alt="image" src="https://github.com/user-attachments/assets/b3a199c6-5c40-478d-9d0a-7ebd770dba12">

The confidence level here must be expressed as 90%/95%/99%.

Replace the word _lies_ with _is_.

**Comment by bryce-carson** [comment]
I'm working on these tasks now, @ashokkrish. At the end of my day I'll let you know what progress I've made on #33. I fully expect all of these tasks to be completed within an hour or so, depending on how much trouble the `align` environment gives me.

*   [ ] Clarify the arithmetical calculation of alpha
*   [ ] Include the degrees of freedom in the subscripts of the chi-square test statistics
*   [ ] Override the automatic centering of the `align` environment for the calculation of the CI, and add a line break between the aligned equations
*   [ ] Parenthesize the CI formula, remove the word "and", and include the degrees of freedom in the subscripts
*   [ ] Fix the display of confidence in the interpretation; the decimal form of the confidence is used when the percentile form is desired
*   [ ] Replace the word "lies" with "is"

**Comment by ashokkrish** [comment]
@bryce-carson 

This is excellent. I look forward to testing the new code.

**Comment by bryce-carson** [comment]
@ashokkrish, I have completed this work. Please see the pushed updated. I will begin work on #33 now.

**Comment by ashokkrish** [comment]
<img width="230" alt="image" src="https://github.com/user-attachments/assets/a81eb951-fa7d-4c56-89a5-52aa4e058f3a">
 
@bryce-carson Could you bring the CI = outside the parentheses

**Comment by ashokkrish** [comment]
<img width="163" alt="image" src="https://github.com/user-attachments/assets/35b7a348-3d3c-4544-93bf-72b60058297c">

Drop the word _where_ and move the df calculation below alpha calculation. So something like this

<img width="166" alt="image" src="https://github.com/user-attachments/assets/326614cd-21dd-473d-89e9-61bc49798ba1">
<img width="162" alt="image" src="https://github.com/user-attachments/assets/1c6516d5-8b93-4cad-b069-4845ac912aec">
<img width="259" alt="image" src="https://github.com/user-attachments/assets/279b719a-baa1-4dea-9ca7-cc559a9821b7">

**Comment by bryce-carson** [comment]
@ashokkrish How is it now? If you'd like further spacing between the lower and upper CIs I can use `\quad` instead of `\;\:`.

**Comment by ashokkrish** [comment]
@bryce-carson The spacing and CL workflow looks good.

I just encountered a validation bug. The sample size n must be greater than 1 (>1). However as it stands with the following numbers the resulting CI produces NaNs.

<img width="253" alt="image" src="https://github.com/user-attachments/assets/483e2f5e-ea76-4385-a55e-71360b08d2ba">
 
<img width="512" alt="image" src="https://github.com/user-attachments/assets/a45ca48c-e315-4809-a2a9-00223117e9ec">

Can you check and fix this please?

**Comment by bryce-carson** [comment]
@ashokkrish, interesting. I'll look at those validation issues.

**Comment by bryce-carson** [comment]
@ashokkrish, I have fixed this issue.

**Comment by bryce-carson** [comment]
> conditional panel exception

A _conditionalPanel_ controls visibility based on a condition, while a shinyvalidate _input validation object_ uses a boolean function and a set of rules to test the validity of an input widget's data. They're separate concerns and concepts, just to refresh your memory.

**Comment by ashokkrish** [comment]
@bryce-carson 

When the user enters

<img width="389" alt="image" src="https://github.com/user-attachments/assets/c37c800b-01b7-41af-92c5-fb0bc0cfabfd">

The app crashes with this error

<img width="411" alt="image" src="https://github.com/user-attachments/assets/4a85e58f-7370-41c2-9463-195004475daa">

Warning: Error in sprintf: invalid format '%d'; use format %f, %e, %g or %a for numeric objects
  101: sprintf
   97: renderUI [C:\Users\ashok\Desktop\CougarStatsApp\CougarStats\R\statInfr.R#4757]
   96: func
   83: renderFunc
   82: output$si-oneSDCI
    1: shiny::runApp

**Comment by bryce-carson** [comment]
> @bryce-carson
> 
> When the user enters
> <img alt="image" width="389" src="https://private-user-images.githubusercontent.com/410949/388379468-c37c800b-01b7-41af-92c5-fb0bc0cfabfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzE2NTQsIm5iZiI6MTczMjE3MTM1NCwicGF0aCI6Ii80MTA5NDkvMzg4Mzc5NDY4LWMzN2M4MDBiLTAxYjctNDFhZi05MmM1LWZiMGJjMGNmYWJmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQwNjQyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjJmNzg0ZmE3ZDlmYmVjZjExOTI1MGIyMmFmN2Q4YWExMTYxY2I0MmU1ZTgyMGQxMzM2NzZhZTJmM2VmZDc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.U3_1kq3NKjbayxsU-J071NNKpxyvwHxhvnzuBKzDVy0">
> 
> The app crashes with this error
> <img alt="image" width="411" src="https://private-user-images.githubusercontent.com/410949/388379570-4a85e58f-7370-41c2-9463-195004475daa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzE2NTQsIm5iZiI6MTczMjE3MTM1NCwicGF0aCI6Ii80MTA5NDkvMzg4Mzc5NTcwLTRhODVlNThmLTczNzAtNDFjMi05NDYzLTE5NTAwNDQ3NWRhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQwNjQyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDNlMWYxNTg4NDlmM2M2M2YzYTk3MGZhZGIzNTZkODQ1Yzk3MzM2N2RmNWEyMTI1ZDFmNGE4MTMwOTM2ZTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7EI-20nHO_Pda4vfXjv-4LYQOHLKBHrxIsowu1ukx8U">
> 
> Warning: Error in sprintf: invalid format '%d'; use format %f, %e, %g or %a for numeric objects 101: sprintf 97: renderUI [C:\Users\ashok\Desktop\CougarStatsApp\CougarStats\R\statInfr.R#4757] 96: func 83: renderFunc 82: output$si-oneSDCI 1: shiny::runApp
> 
> If you look at inference for one population mean (mu) you will notice there is an extra layer of instant validation on non-integer sample size entries.
> <img alt="image" width="388" src="https://private-user-images.githubusercontent.com/410949/388380143-b633c9b5-af62-4ed0-ac14-00ea80f61e25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzE2NTQsIm5iZiI6MTczMjE3MTM1NCwicGF0aCI6Ii80MTA5NDkvMzg4MzgwMTQzLWI2MzNjOWI1LWFmNjItNGVkMC1hYzE0LTAwZWE4MGY2MWUyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQwNjQyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmZjZmFkZjc2ODdkYjU5ZWQ3MTc2ODc2YzdmMDIzYzJmNzM5MzEzMDczNjRhOGExNTIxNjljOGVkODc4OTkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nZf3H3S9mOmvVZx463QE5Ed5qhEBwmpf3Ihb42af3lM">

Thanks, I will get that done tomorrow morning.
